import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import { Toaster } from "@/components/ui/sonner";

import "react-loading-skeleton/dist/skeleton.css";
import "simplebar-react/dist/simplebar.min.css"

import { OctagonX } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="light"
    >
      <Providers>
        <body className={cn("min-h-screen font-sans antialiased grainy", geistSans.className)}>
          <Toaster
            icons={{
              error: <OctagonX className="text-red-900 h-4 w-"/>,
            }}
            toastOptions={{
              style: {
                background: '#ffe2e0',
                border: '#ffe2e0'
              },
              classNames: {
                title: '!text-red-900',
                description: '!text-red-900',
              },
            }} />
          <Navbar />
          {children}
        </body>
      </Providers>
    </html>
  );
}
